### ISSUE TITLE
Prepare custom dataset for PatchMixer

### ISSUE THREAD

**Issue by younis-amb** [Zeying-Gong/PatchMixer#7]
I have a sales transactional data and I want to test PatchMixer on it. How can I prepare the data for it.

**Comment by Zeying-Gong** [comment]
To prepare the custom dataset, you can follow the steps below:

1. Place the dataset (.csv file) in the `dataset/` directory.
2. Set `--data` attribute to  'custom', which specifies that the dataset's partitioning is determined by `Dataset_Custom` (defined in `data_factory.py`).
3. Set the `--data_path` attribute to the csv file. 
4. Other configurations can be referenced from the weather, electricity, or traffic datasets.

Please note that this code follows the data reading framework established by the Informer, and the process for custom dataset preparation should be similar or the same.
